### ISSUE TITLE
Datasource names are printed even when not using --verbose.

### ISSUE THREAD

**Issue by omadawn** [grafana-tools/grafana-backup#13]
Simple fix.

**Comment by grafov** [comment]
Thank you!

Sorry for long delays with the response. I am very busy with work till EOY. It seems my opensource projects postponed until New Year holidays. @omadawn I appreciate with the changes you are made so if you still interested with the project I would grant you direct access on write to `grafana-backup` repo. So  my absence will not stop the project contributions.

**Comment by omadawn** [comment]
That's perfectly understandable. The same thing happens to me all the time. The only reason I'm able to submit so much to this project right now is because I'm gearing it up to be used to keep my production environment backed up so I get to work on it during the day. That's why I was very excited to find your project. Not only does it give me several weeks of head start on a backup solution but it's clean and clear enough for me to contribute back and hopefully benefit other folks. 

Direct access would be great. I have a few changes I still want to submit (but have been able to focus on other things.) If you're going to be swamped until the end of the year I'll pass them by a couple of my coworkers for at least a sniff test before I approve any of my own changes. ^_^
