### ISSUE TITLE
Restore example

### ISSUE THREAD

**Issue by cabrinoob** [grafana-tools/grafana-backup#15]
Hi,
I'am trying to use grafana-backup to backup and restore my grafana dashboards.

The backup works fine but I don't know how tu use the restore method.

**I want to use it from docker**. 

For the backup I'am using this : 

```
docker run --rm --name grafana-backup-tool \
   -e GRAFANA_TOKEN={YOUR_GRAFANA_TOKEN} \
   -e GRAFANA_URL={YOUR_GRAFANA_URL} \
   -v {YOUR_BACKUP_FOLDER_ON_THE_HOST}:/opt/grafana-backup-tool/_OUTPUT_  \
   ysde/docker-grafana-backup-tool
```
But for the restore I don't know what to do. When I look inside the Dockerfile I see that there is an ENTRYPOINT assigned to **backup_grafana.sh**.

thank you for your help

**Comment by grafov** [comment]
The issue related to Python utility with the same name.

**Comment by cabrinoob** [comment]
Yes sorry, I realized it too late and I was not able to delete this inapropriate issue, so I closed it.
Sorry again

**Comment by grafov** [comment]
No problem!
