### ISSUE TITLE
Add a command line flag to specify a default output directory

### ISSUE THREAD

**Issue by omadawn** [grafana-tools/grafana-backup#2]
I don't know about you but when I download some go code for the first time I usually end up running it from within the directory itself at least the first few times. That can make things a little awkward when a command dumps a whole lot of files into CWD.

I'd like a -dir flag which has a default value, perhaps "backups" and already have code to implement it.

**Comment by grafov** [comment]
Default dir is reasonable behavior for safety. I will implement it or you could add PR.

**Comment by grafov** [comment]
Thank you! And check my last comment for the #13.
